### PR TITLE
Speedup test

### PR DESCRIPTION
**Pull request by sonots**
Reduce sleep period

### CODE REVIEW

**Comment by civitaspo** [comment]
oh, excuse me. Could you rebase it?

**Comment by sonots** [comment]
@civitaspo rebased

**Comment by civitaspo** [comment]
ok! merged.

**Comment by civitaspo** [comment]
shiped https://github.com/civitaspo/fluent-plugin-cat-sweep/commit/83df69852433db8764cfa47bd0e7c7bffdbb2ba3 https://rubygems.org/gems/fluent-plugin-cat-sweep

**Pull request merged**
