### PR TITLE
upgrade fluentd version for new configuration style

### PR DESCRIPTION
**Pull request by karupanerura**
see: https://docs.fluentd.org/plugin-development/plugin-update-from-v0.12

### CODE REVIEW

**Comment by civitaspo** [comment]
Thank you so much for your contribution. This change is very helpful for me. But some test cases are failed. Could you check them?

**Comment by karupanerura** [comment]
Of course! it looks like random failure. This problem is occurred by the unstable test driver emulation. 
So I commited 816f7a0. please check again!

**Comment by civitaspo** [comment]
LGTM. I will release a new version `v0.2.0`. Wait for a while.

**Comment by civitaspo** [comment]
Shipped. https://rubygems.org/gems/fluent-plugin-cat-sweep/versions/0.2.0

**Comment by karupanerura** [comment]
It works! Thank you so much!

**Pull request merged**
